name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Instalar dependencias necesarias para el despliegue.
          # npm install

      - name: Build project
        run: |
          # Construir el proyecto.
          # npm run build

      - name: Deploy to production
        run: |
          # Comandos para desplegar la aplicación en el entorno de producción.